"""Emit a per-artefact LaTeX longtable from partition.json and coverage.csv."""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTITION = ROOT / "sample_results" / "partition.json"
COVERAGE = ROOT / "vocabulary" / "coverage.csv"
DST = ROOT / "sample_results" / "artefact_coverage_table.tex"

UNKNOWN_PREFIX = "Unknown_"
PLATFORM_COMPONENTS = ("Schema", "Lifecycle", "Schema+Lifecycle",
                       "Lifecycle+Chain", "Schema+Lifecycle+Chain", "Chain")
QUOTE_MAX = 110


def _is_fully_canonicalised(entry: dict) -> bool:
    return not (entry["bearer"].startswith(UNKNOWN_PREFIX)
                or entry["predicate"].startswith(UNKNOWN_PREFIX)
                or entry["artefact"].startswith(UNKNOWN_PREFIX))


def _coverage_lookup() -> dict[str, dict]:
    out: dict[str, dict] = {}
    with COVERAGE.open() as f:
        for r in csv.DictReader(f):
            out[r["artefact"]] = r
    return out


def _tex_escape(s: str) -> str:
    out = s.replace("\\", r"\textbackslash{}")
    for a, b in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        out = out.replace(a, b)
    repl = {"–": "--", "—": "---",
            "‘": "`", "’": "'", "“": "``", "”": "''",
            " ": " ", "­": "", "·": r"$\cdot$", "•": r"$\bullet$",
            "…": r"\ldots{}"}
    for a, b in repl.items():
        out = out.replace(a, b)
    return out


def _shorten(text: str, max_chars: int) -> str:
    text = " ".join(text.split())
    if len(text) > max_chars:
        text = text[:max_chars].rstrip(" ,;:") + "…"
    return text


def _representative_quote(provisions: list[dict]) -> str:
    """Shortest verbatim from the provision with the most sources."""
    if not provisions:
        return ""
    most_common = max(provisions, key=lambda p: len(p["sources"]))
    verbatims = sorted(most_common["verbatims"], key=len)
    return verbatims[0] if verbatims else ""


def main() -> int:
    cov = _coverage_lookup()
    part = json.loads(PARTITION.read_text())

    by_artefact: dict[str, list[dict]] = defaultdict(list)
    for entry in part:
        if _is_fully_canonicalised(entry):
            by_artefact[entry["artefact"]].append(entry)

    rows: list[dict] = []
    for artefact in sorted(by_artefact.keys()):
        c = cov.get(artefact)
        if not c or c["smart_component"] not in PLATFORM_COMPONENTS:
            continue
        provisions = by_artefact[artefact]
        n_quotes = sum(len(p["sources"]) for p in provisions)
        rows.append({
            "artefact": artefact,
            "smart_component": c["smart_component"],
            "smart_section": c["smart_section"],
            "n_provisions": len(provisions),
            "n_quotes": n_quotes,
            "example_quote": _representative_quote(provisions),
        })

    comp_order = {c: i for i, c in enumerate(PLATFORM_COMPONENTS)}
    rows.sort(key=lambda r: (comp_order.get(r["smart_component"], 99),
                              -r["n_provisions"], r["artefact"]))

    out: list[str] = []
    out.append("% =============================================================================")
    out.append("% Per-artefact SMART coverage with verbatim source evidence.")
    out.append("% Auto-generated by scripts/artefact_coverage_table.py.")
    out.append("% Drop-in: \\input{requirements-analysis/sample_results/artefact_coverage_table.tex}")
    out.append("% Requires longtable + booktabs + a \\small or \\scriptsize wrapper if needed.")
    out.append("% =============================================================================")
    out.append("")
    out.append(r"\begin{longtable}{p{0.18\textwidth} p{0.10\textwidth} p{0.13\textwidth} r r p{0.36\textwidth}}")
    out.append(r"\caption{Per-artefact SMART platform coverage with verbatim "
               r"source evidence. Each row is one canonical artefact in the "
               r"closed vocabulary that (a)~appears in at least one fully "
               r"canonicalised provision in the corpus and (b)~maps to a "
               r"real SMART component in \texttt{vocabulary/coverage.csv}. "
               r"\emph{Distinct provisions} counts canonical "
               r"\texttt{(bearer, predicate, artefact)} triples that "
               r"reference the artefact (different actor/action combinations "
               r"over the same artefact category). \emph{Source quotes} "
               r"counts the (paragraph, verbatim) pairs that produced those "
               r"provisions. The \emph{example quote} is the shortest "
               r"verbatim from the most-restated provision for that artefact "
               r"and is taken directly from the source PDF.\label{tab:artefact-coverage}} \\")
    out.append(r"\toprule")
    out.append(r"Artefact & Component & Section & \multicolumn{1}{c}{\#\,Provisions} & \multicolumn{1}{c}{\#\,Quotes} & Example source quote (verbatim) \\")
    out.append(r"\midrule")
    out.append(r"\endfirsthead")
    out.append(r"\multicolumn{6}{c}{\tablename\ \thetable{} -- continued} \\")
    out.append(r"\toprule")
    out.append(r"Artefact & Component & Section & \multicolumn{1}{c}{\#\,Provisions} & \multicolumn{1}{c}{\#\,Quotes} & Example source quote (verbatim) \\")
    out.append(r"\midrule")
    out.append(r"\endhead")
    out.append(r"\bottomrule")
    out.append(r"\endfoot")
    for r in rows:
        out.append(
            rf"\texttt{{{_tex_escape(r['artefact'])}}} & "
            rf"\texttt{{{_tex_escape(r['smart_component'])}}} & "
            rf"{_tex_escape(r['smart_section'])} & "
            rf"{r['n_provisions']} & "
            rf"{r['n_quotes']} & "
            rf"\emph{{``{_tex_escape(_shorten(r['example_quote'], QUOTE_MAX))}''}} \\"
        )
    out.append(r"\end{longtable}")
    out.append("")

    DST.write_text("\n".join(out))
    print(f"wrote {DST}  ({len(rows)} rows)")
    print(f"  in-scope artefacts: {len(rows)}")
    print(f"  total distinct provisions: {sum(r['n_provisions'] for r in rows)}")
    print(f"  total source quotes: {sum(r['n_quotes'] for r in rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
