"""Build a per-artefact Markdown evidence document with verbatim source quotes."""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTITION = ROOT / "sample_results" / "partition.json"
COVERAGE = ROOT / "vocabulary" / "coverage.csv"
DST = ROOT / "sample_results" / "coverage_evidence.md"

UNKNOWN_PREFIX = "Unknown_"
DOC_NAMES = {
    "eu_ai_act_2024_1689":      "EU AI Act 2024/1689",
    "eu_mdr_2017_745":          "EU MDR 2017/745",
    "fda_ai_ml_action_plan_2021": "FDA AI/ML SaMD Action Plan (2021)",
    "fda_pccp_guidance_2024":   "FDA PCCP guidance (2024)",
    "fda_lifecycle_draft_2025": "FDA lifecycle management draft guidance (2025)",
    "tripod_ai_2024":           "TRIPOD+AI (2024)",
}
MAX_QUOTE_CHARS = 600


def _is_fully_canonicalised(entry: dict) -> bool:
    return not (entry["bearer"].startswith(UNKNOWN_PREFIX)
                or entry["predicate"].startswith(UNKNOWN_PREFIX)
                or entry["artefact"].startswith(UNKNOWN_PREFIX))


def _coverage_lookup() -> dict[str, dict]:
    out: dict[str, dict] = {}
    with COVERAGE.open() as f:
        for r in csv.DictReader(f):
            out[r["artefact"]] = r
    return out


def _format_quote(text: str) -> str:
    text = " ".join(text.split())
    if len(text) > MAX_QUOTE_CHARS:
        text = text[:MAX_QUOTE_CHARS].rstrip() + "…"
    return "> " + text


def main() -> int:
    part = json.loads(PARTITION.read_text())
    cov = _coverage_lookup()

    by_artefact: dict[str, list[tuple]] = defaultdict(list)
    for entry in part:
        if not _is_fully_canonicalised(entry):
            continue
        triple = (entry["bearer"], entry["predicate"], entry["artefact"])
        for (doc, loc), verbatim in zip(entry["sources"], entry["verbatims"]):
            by_artefact[entry["artefact"]].append((triple, doc, loc, verbatim))

    out: list[str] = []
    out.append("# Coverage evidence — verbatim source quotes per artefact")
    out.append("")
    out.append(
        "Each section below shows one canonical artefact, the SMART platform "
        "section/component it maps to (from `vocabulary/coverage.csv`), and "
        "the **exact source-paragraph quotes** that produced canonical "
        "provisions referencing it. Each regulator uses its own terminology "
        "for the underlying obligations (EU MDR — GSPR; EU AI Act — "
        "obligations and technical-documentation requirements; FDA — "
        "submission elements / recommendations; TRIPOD+AI — reporting "
        "items). The quotes are quoted verbatim from the corpus PDFs and "
        "let a reader verify the mapping without relying on the researcher's "
        "English `note` summary.")
    out.append("")
    out.append("Generated by `scripts/coverage_evidence.py` from "
               "`sample_results/partition.json` + `vocabulary/coverage.csv`. "
               "Runs end-to-end with no LLM calls.")
    out.append("")

    n_artefacts_total = 0
    n_artefacts_in_scope = 0

    PLATFORM_COMPONENTS = {"Schema", "Lifecycle", "Schema+Lifecycle",
                            "Lifecycle+Chain", "Schema+Lifecycle+Chain", "Chain"}
    in_scope: list[str] = []
    out_of_scope: list[str] = []
    for artefact in sorted(by_artefact.keys()):
        c = cov.get(artefact)
        if c and c["smart_component"] in PLATFORM_COMPONENTS:
            in_scope.append(artefact)
        else:
            out_of_scope.append(artefact)

    n_artefacts_total = len(in_scope) + len(out_of_scope)
    n_artefacts_in_scope = len(in_scope)

    def _section(artefact: str) -> None:
        c = cov.get(artefact, {})
        evidences = by_artefact[artefact]
        out.append(f"## `{artefact}`")
        out.append("")
        out.append(f"- **SMART section:** {c.get('smart_section') or '—'}")
        out.append(f"- **SMART component:** `{c.get('smart_component') or '—'}`")
        if c.get("note"):
            out.append(f"- **Researcher note:** {c['note']}")
        out.append(f"- **Distinct canonical provisions referencing this artefact:** "
                   f"{len({ev[0] for ev in evidences})}")
        out.append(f"- **Source-paragraph quotes:** {len(evidences)}")
        out.append("")

        by_doc: dict[str, list[tuple]] = defaultdict(list)
        for ev in evidences:
            by_doc[ev[1]].append(ev)
        for doc in sorted(by_doc.keys()):
            doc_label = DOC_NAMES.get(doc, doc)
            out.append(f"### Quotes from {doc_label}")
            out.append("")
            seen: set[tuple] = set()
            for triple, _, locator, verbatim in sorted(by_doc[doc], key=lambda e: e[2]):
                key = (locator, verbatim)
                if key in seen:
                    continue
                seen.add(key)
                triple_str = f"({triple[0]}, {triple[1]}, {triple[2]})"
                out.append(f"- *{locator}* — establishes provision `{triple_str}`")
                out.append("  " + _format_quote(verbatim).replace("\n", "\n  "))
                out.append("")

    out.append(f"## Summary")
    out.append("")
    out.append("| | # |")
    out.append("|---|---|")
    out.append(f"| Distinct artefacts with at least one canonical provision | {n_artefacts_total} |")
    out.append(f"| In SMART scope (Schema, Lifecycle, Chain, or combo) | {n_artefacts_in_scope} |")
    out.append(f"| Recognised but out-of-scope (`smart_component = N/A` or missing) | {n_artefacts_total - n_artefacts_in_scope} |")
    out.append("")

    out.append(f"# In-scope artefacts ({len(in_scope)})")
    out.append("")
    for a in in_scope:
        _section(a)

    out.append(f"# Out-of-scope artefacts ({len(out_of_scope)})")
    out.append("")
    out.append("These artefacts have canonical provisions in the corpus but the "
               "SMART platform does not attest them — typically because the "
               "obligation falls on a party other than the model-card author "
               "(authority-side investigations, regulator submission portals, etc.).")
    out.append("")
    for a in out_of_scope:
        _section(a)

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out))
    print(f"wrote {DST}")
    print(f"  artefacts in-scope:     {n_artefacts_in_scope}")
    print(f"  artefacts out-of-scope: {n_artefacts_total - n_artefacts_in_scope}")
    print(f"  total quotes embedded:  "
          f"{sum(len(by_artefact[a]) for a in by_artefact)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
